

services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  urlshortner:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

volumes:
  redis-data:
