# Spring Application Name
spring.application.name=UrlShortner

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://nn9619807_db_user:DKWSMIrAoAsyYNHm@cluster0.c5v9d3y.mongodb.net/urldata?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# Redis Configuration

spring.data.redis.host=redis-12372.c80.us-east-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=12372
spring.data.redis.password=aGltjUDFa31tL3TSmZicPEp419rqMZE8

# Server Configuration
server.port=8080

# Backend URL
backend.url=https://u-eqrw.onrender.com/
