# Spring Application Name
spring.application.name=UrlShortner

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://nn9619807:root@cluster0.84afbld.mongodb.net/UrlData?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.auto-index-creation=true

# Redis Configuration

spring.data.redis.host=redis-18156.crce206.ap-south-1-1.ec2.redns.redis-cloud.com
spring.data.redis.port=18156
spring.data.redis.password=RkHcC2PlQdX4GXa6S12IiVyf8tJalMft

# Server Configuration
server.port=8080

# Backend URL
backend.url=https://u-eqrw.onrender.com/
