# Spring Application Name
spring.application.name=UrlShortner

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://naresh:root@ushortcluster.u7ui5.mongodb.net/UrlData?retryWrites=true&w=majority&appName=USHORTCluster

# Redis Configuration

spring.data.redis.host=redis-15067.c264.ap-south-1-1.ec2.redns.redis-cloud.com
spring.data.redis.port=15067
spring.data.redis.password=THHvjW58zB8sl4jHzw6bTZRGuYWV57cN

# Server Configuration
server.port=8080

# Backend URL
backend.url=https://urlshortnerbackend-lr9r.onrender.com/
